# Config file for Google APp Engine

version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: flask
  version: latest
- name: youtube-dl
  version: latest
- name: pafy
  version: latest
    
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: app.py
